# Generated by Django 3.2.21 on 2025-04-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_customuser'),
        ('content', '0003_add_default_categories'),
    ]

    operations = [
    ]
