# Generated by Django 3.2.21 on 2025-04-15 07:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_merge_0002_customuser_0003_add_default_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('life', 'Lifestyle'), ('news', 'News'), ('health', 'Health'), ('edu', 'Education'), ('other', 'Other')], default='other', max_length=32, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Write your blog content here...'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.BooleanField(default=True, help_text='Will this post be published?', verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='untitled-blog', max_length=256, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='default-thumbnail.png', upload_to='content/blog/thumbnail/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Untitled Blog', max_length=256, unique=True, verbose_name='Title'),
        ),
    ]
