# Generated by Django 3.2.25 on 2025-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20250415_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='audio',
            field=models.CharField(default='https://www.youtube.com/embed/dQw4w9WgXcQ', max_length=256, verbose_name='Video link :'),
        ),
    ]
